using JetBrains.Annotations;

namespace Blueprint
{
    /// <summary>
    /// A simple marker interface that is used to identify operations that can be executed in the system, an
    /// operation being defined as a simple property bag with parameters, metadata in the form of attributes, and
    /// an association <see cref="IApiOperationHandler{T}"/>.
    /// </summary>
    [UsedImplicitly(ImplicitUseKindFlags.InstantiatedNoFixedConstructorSignature, ImplicitUseTargetFlags.WithMembers)]
    public interface IApiOperation
    {
    }

    /// <summary>
    /// An extension of <see cref="IApiOperation" /> that specifies the response type that will be generated by
    /// the operation.
    /// </summary>
    /// <typeparam name="TResponse">The type of response that will be generated.</typeparam>
    [UsedImplicitly(ImplicitUseKindFlags.InstantiatedNoFixedConstructorSignature, ImplicitUseTargetFlags.WithMembers)]
    public interface IApiOperation<TResponse> : IApiOperation
    {
    }
}
