name: Blueprint Release

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1

on:
  push:
    tags:
    - 'v*'

jobs:
  tagged-release:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup .NET SDK 6.0.x
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: '6.0.x'

      - name: dotnet pack
        run: dotnet pack --configuration Release --output ${{ github.workspace }}/.nupkgs -verbosity:minimal
        if: ${{ success() && github.event_name != 'pull_request' }}

      - name: dotnet nuget push
        run: dotnet nuget push "*.nupkg" --source "https://api.nuget.org/v3/index.json" --api-key "$env:TOKEN"
        env:
          TOKEN: ${{ secrets.NUGET_TOKEN }}
        working-directory: ${{ github.workspace }}/.nupkgs
        if: ${{ success() && github.event_name != 'pull_request' }}

      - name: Tagged Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
        if: ${{ success() && github.event_name != 'pull_request' }}
