name: Build Blueprint

# Build Variables
env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  Prerelease: ci
  BuildConfiguration: Release

## CI Trigger on master branch
on:
  push:
    branches:
      - master
      - feature/github-actions
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
      - '**/*.md'

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        dotnet-version: [ '5.0.x', '3.1.x' ]

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET SDK ${{ matrix.dotnet }}
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ matrix.dotnet-version }}

    #- name: SonarCloud Preparation
    #  uses: sonarsource/sonarcloud-github-action@master
    #  env:
    #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: dotnet restore
      run: dotnet restore

    - name: dotnet build
      run: dotnet build --configuration ${{ env.BuildConfiguration }} -p:Prerelease=${{ env.Prerelease }} --no-restore

    - name: dotnet test
      run: dotnet test --configuration ${{ env.BuildConfiguration }} -p:Prerelease=${{ env.Prerelease }} --no-build --no-restore --collect "Code coverage"

    - name: dotnet pack
      run: dotnet pack ./<project>/.nupkgs -v:minimal --no-build
      if: ${{ success() && github.event_name != 'pull_request' }}

    #- name: dotnet nuget push
    #  run: dotnet nuget push ./<project>/.nupkgs/*.nupkg
    #  with:
    #    command: push
    #    packagesToPush: $(Build.ArtifactStagingDirectory)/.nupkgs/*.nupkg
    #    nuGetFeedType: internal
    #    publishVstsFeed: 91817c8d-b32d-4cea-8df3-57127121c593/1252a847-6abc-49a4-80ad-001f8ee7fd4c
    #    allowPackageConflicts: true
    #  if: ${{ success() && github.event_name != 'pull_request' }}

    #- name: Analyze with SonarCloud
    #  uses: sonarsource/sonarcloud-github-action@master

    #- name: Publish SonarCloud results
    #  uses: actions/SonarCloudPublish@1
    #  with:
    #    pollingTimeoutSec: '300'
